# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b0c7498bdd11b0a99fb4e0e1456dd571f98ee9c2da3a4aa987881a94efb734711ca0eb4839bc52760f90a31d233014d05609f31414e29a808723cbcad4555ba

test:
  secret_key_base: 013cd5ac179cde1b4840e24b4ac90b601743c6f1a7d93bc29f35c2d526090cb9fb08475d8714d02ba058753cb3132bde151c3ca48a23ead815e8703b0182c0c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
